layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: cjunius
  linkedin: cjunius
  # medium: @your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # youtube: your_username

topics:
  - name: React JS
    web_url: https://reactjs.org/
    image_url: 

  - name: Amazon Web Services
    web_url: https://aws.amazon.com/
    image_url: http://www.logospng.com/images/29/amazonwebservices-logosvg-wikimedia-commons-29486.png

  - name: Docker
    web_url: https://www.docker.com
    image_url: https://www.docker.com/sites/default/files/social/docker_facebook_share.png
   
  - name: iOS
    web_url: https://www.apple.com/ios
    image_url: https://img.icons8.com/color/1600/ios-logo.png
    
  - name: Android
    web_url: https://www.android.com
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Android_robot.svg/511px-Android_robot.svg.png
