source "https://rubygems.org"
ruby "3.1.4"
gem "jekyll"
gem "jekyll-feed"
gem "jekyll-paginate-v2"
gem "jekyll-seo-tag"
gem "webrick"
gem 'github-pages', group: :jekyll_plugins
gem "jekyll-github-metadata"
gem "jekyll-octicons"
gem "jemoji"
